### ISSUE TITLE
Version history table in release notes is not generated in translated docs

### ISSUE THREAD

**Issue by SooluThomas** [Qiskit/qiskit-metapackage#1008]
## Did you find a doc bug or broken link that needs to be fixed?

English Qiskit Docs: https://qiskit.org/documentation/release_notes.html#id187
Korean Qiskit Docs: https://qiskit.org/documentation/locale/ko_KR/release_notes.html#id155

We probably might want to generate the version history table in all docs.

**Comment by mtreinish** [comment]
To fix this you'll need to modify the version history table sphinx extension: https://github.com/Qiskit/qiskit/blob/master/docs/versionutils.py#L75-L175 to use the git history from github instead of a local checkout. It was originally written assuming that it would be run from the qiskit repository and could just run git from the sphinx build dir and access the tags and historical setup.py files. This doesn't work for the translated docs because they've been moved to a separate repository so when the extension runs in `qiskit-community/qiskit-translations` it does `git tag` which returns an empty list. It shouldn't be too hard to do, basically just add a git clone step to a tmpdir and use that local checkout for all the git operations in the extension.

**Comment by SooluThomas** [comment]
Thank you

**Comment by nonhermitian** [comment]
Closing as it appears to be solved.
