### ISSUE TITLE
qiskit on mobile

### ISSUE THREAD

**Issue by haareks** [Qiskit/qiskit-metapackage#1009]
I cant figure out, how to install qiskit on android.

Userland + ubuntu and termux are not working out.

How can one install qiskit on android mobile?

**Comment by mtreinish** [comment]
Android via termux (or otherwise) is an unsupported platform, mostly because most of the tooling qiskit is built on doesn't support it natively. That being said it should be possible, but it will be a more involved because qiskit has compiled extensions and many of it's dependencies do as well. I don't think the android target via termux is supported by pypa/pip/pypi so there will not be any precompiled binaries available (unless the manylinux aarch64 target will work on your device which requires armv8 and a compatible userspace) and you'll have to build everything from source. In termux you'll have to go through: https://qiskit.org/documentation/contributing_to_qiskit.html#installing-from-source for qiskit but also for every dependency that has a compiled extension. For example one of terra's dependencies is retworkx: https://retworkx.readthedocs.io/en/stable/README.html#building-from-source there's also numpy, scipy, etc There might be termux packages available for some (like numpy and scipy do), but probably not all.

**Comment by divshacker** [comment]
You can use Google colab if you want to use qiskit in mobile as it use computer specs in back-end . And it will also provide you better processing power than your android phone.

**Comment by nonhermitian** [comment]
Closing as stale.
