### ISSUE TITLE
Cannot pip install qiskit==0.21 on mac osx in new conda env due to rust compiler 

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#1046]
### Informations

- **Qiskit version**: 0.21
- **Python version**: 3.7.9
- **Operating system**: OQX

### What is the current behavior?
```python

  Building wheel for retworkx (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/miniconda3/envs/qiskit21/bin/python /opt/miniconda3/envs/qiskit21/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/bm/8lm02z6d5cn6myhc11gjh1ch0000gn/T/tmprnpayzcc
       cwd: /private/var/folders/bm/8lm02z6d5cn6myhc11gjh1ch0000gn/T/pip-install-zbx0k79o/retworkx
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/retworkx
  copying retworkx/__init__.py -> build/lib/retworkx
  running egg_info
  writing retworkx.egg-info/PKG-INFO
  writing dependency_links to retworkx.egg-info/dependency_links.txt
  writing requirements to retworkx.egg-info/requires.txt
  writing top-level names to retworkx.egg-info/top_level.txt
  reading manifest file 'retworkx.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'retworkx.egg-info/SOURCES.txt'
  running build_ext
  running build_rust
  error: Can not find Rust compiler
  ----------------------------------------
  ERROR: Failed building wheel for retworkx
Successfully built qiskit
Failed to build retworkx
ERROR: Could not build wheels for retworkx which use PEP 517 and cannot be installed directly
```

### Steps to reproduce the problem
Create new conda env and do `pip install qiskit==0.21`

### What is the expected behavior?
It works.

**Comment by mtreinish** [comment]
This was a temporary failure I just released retworkx 0.5.0 a few minutes ago. The sdist is the fastest to generate and it took a few minutes for CI to build the macOS binaries. In that window between the sdist uploading and the macOS binaries being on PyPi pip defaults to the latest version and tries to install retworkx from source/sdist instead of falling back to 0.4.0 which has wheels available. Regardless the macOS binaries are up now https://pypi.org/project/retworkx/#files so if you try again this should work. I'm closing because I don't think there is anything to fix here. Please feel free to reopen if I'm missing something.
