### ISSUE TITLE
Remove source code from Qiskit Documentation

### ISSUE THREAD

**Issue by ikkoham** [Qiskit/qiskit-metapackage#1168]
### What is the expected behavior?

I propose that source codes are removed from Qiskit documentation. (e.g. https://qiskit.org/documentation/_modules/qiskit/circuit/quantumregister.html#AncillaQubit)
Instead, how about making the link to source codes of GitHub corresponding to commit hash?

Advantage
- light docs

Disadvantage
- Cannot make the link from source  to docs

**Comment by nonhermitian** [comment]
Is there some reason why this is needed?

**Comment by ikkoham** [comment]
I don't have a significant reason, but I feel the size of the docs is very large and I prefer the source code to be a link to GitHub like NumPy (e.g. https://numpy.org/doc/1.20/reference/generated/numpy.ones.html).
This is just my preference, so if you don't like please close this issue.

**Comment by nonhermitian** [comment]
I see what your looking for.  Unfortunately, unlike NumPy, the docs are sourced from multiple Github repos.  Therefore it would take quite a bit of tooling to get Sphinx to understand where everything comes from.  Once we draw our docs from a single source repo then what you are asking for is straightforward to do.

Closing since we can not do much until that time.

**Comment by ikkoham** [comment]
Thank you for your consideration :)
