### ISSUE TITLE
Include environment variable option for location of directory containing config files

### ISSUE THREAD

**Issue by paniash** [Qiskit/qiskit-metapackage#1217]
### What is the expected behavior?

The environment variable `QISKIT_SETTINGS` exists for specifying the location of the ini file `settings.conf`. However, this file is present within the directory `~/.qiskit/` which is inside the home directory (which also contains `qiskitrc` for IBMQ login details).

I suggest having an environment variable for specifying the location of this directory (`~/.qiskit/`) elsewhere instead. Over the past few years, a growing set of software follow the [XDG base specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) so as to not clutter the home directory and accordingly make sure that their respective config files lie in the directory `~/.config/`

My suggestion would be to either make the location `~/.config/qiskit/` by default or give the users an option (via environment variable or something else suitable) to change the location of this directory.

**Comment by amitracal** [comment]
Are you saying qiskitrc is a qiskit profile & the QISKIT_SETTINGS is inside this qiskitrc, which needs to be moved to  ~/.config/qiskit/  ? if so can you assign this to me?

**Comment by paniash** [comment]
@amitracal What I mean is that instead of the config directory being `~/.qiskit/`, a preferrable location as per the OP would be `~/.config/qiskit/`. Please feel free to work on it. Thanks!

**Comment by jakelishman** [comment]
The `QISKIT_SETTINGS` environment variable already completely controls the location of Terra's `settings.conf`, so it can be used to put the file anywhere desired.  The other part is that IBMQ Provider's `qiskitrc` file had a hard-coded location.  That could have been more controlled, but since IBMQ Provider is now deprecated, we won't be merging any more features to it.

I'll close this issue now because the requested feature on Terra already exists, and the violator of it is deprecated pending removal.  Please feel free to re-open on Terra if there's more to be discussed.
