### ISSUE TITLE
Wrong definition of RZ in qiskit textbook, is the phase gate P

### ISSUE THREAD

**Issue by Costor** [Qiskit/qiskit-metapackage#1269]
Hi,
I believe the Qiskit textbook gives a wrong definition of RZ [here](https://qiskit.org/textbook/ch-states/single-qubit-gates.html#5.-The-R%CF%95-gate--) in the chapter on simple gates and Rphi alias RZ.
What is described there by the explicit matrix definition is actually the phase gate P [PhaseGate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.PhaseGate.html#qiskit-circuit-library-phasegate). Also the statement RZ(pi)=Z is not true, it would be correct for P(pi)=Z.  The actual definition of the RZ-gate is [RZGate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.RZGate.html#qiskit-circuit-library-rzgate).

So you might either correct every notion of Rphi or RZ into P at this location,  or correct the matrix representation and remove the statement RZ(pi)=Z.

Note that though RZ and P only differ by a phase factor they are not replacements of each other: the phase difference factor becomes crucial in qubit dimensions > 1, e.g. in controlled gates, see e.g. explanation in CRZ [documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CPhaseGate.html#qiskit-circuit-library-cphasegate) and CP [documentation](https://qiskit.org/documentation/stubs/qiskit.circuit.library.CPhaseGate.html#qiskit-circuit-library-cphasegate) this!

**Comment by mtreinish** [comment]
Hi, thanks for opening this issue. I believe you opened this on the wrong repository. This repository is for the qiskit documentation and the metapackage (the python package which installs all the qiskit components at once). If you want to report an issue in the qiskit-textbook you should open an issue here: https://github.com/qiskit-community/qiskit-textbook/issues/new/choose

Normally I would just transfer this issue to the correct repository for you, but unfortunately I'm not able to do that because the textbook repository is in a separate github organization (and github doesn't let you transfer between organizations). So I'm going to close this issue here. But, please feel free to reopen it if I'm mistaken or there is more to discuss on this here.

**Comment by Costor** [comment]
Ok thanks, I moved it over!
