### ISSUE TITLE
No module named 'qiskit.chemistry'

### ISSUE THREAD

**Issue by rajarshiche** [Qiskit/qiskit-metapackage#1398]
I installed qiskit according to the stated guidelines (from qiskit website) using Anaconda on Windows. However, when I am trying to import any of the qiskit.chemistry packages, it says " ModuleNotFoundError: No module named 'qiskit.chemistry' ". When I am trying to install with 'pip install qiskit-chemistry', the installation does not work. How can I install/import/use qiskit.chemistry packages then?

Thanks,
Raj

**Comment by jakelishman** [comment]
Qiskit Chemistry was transitioned into a new repository called "Qiskit Nature" a little while back - you'll want to do `pip install qiskit[nature]` or `pip install qiskit-nature`, and then you can have a look at [its documentation](https://qiskit.org/documentation/nature/) for more.

**Comment by woodsp-ibm** [comment]
As stated above the chemistry function, that was part of Qiskit Aqua applications and algorithms package,  was moved/refactored to Qiskit Nature. Qiskit Aqua was deprecated last April to allow time for migration, before its ultimate removal, but now support has  ended and the package is no longer provided.

Now I understand there are examples/videos out there which were done some while ago that still show/use the chemistry code. Ideally if you can find one done for the newer Nature, if that its examples/videos you are looking at following, that would be the best way to go. The documentation linked above has Tutorials for Nature. If somehow you absolutely have to have chemistry then you could install an older version of Qiskit where Aqua/chemistry still exists. Though the "right way" is to move to Nature as this is the path forward - installing some older version, that is no longer supported/provided would just be some expedient solution I think if it were absolutely necessary.

**Comment by rajarshiche** [comment]
Thanks a ton @jakelishman and @woodsp-ibm for the detail clarification. Qiskit Nature works indeed. However, some guidance will be highly appreciated in installing 'PySCF' library on windows. The case example given at https://github.com/Qiskit/qiskit-nature ("Creating Your First Chemistry Programming Experiment in Qiskit") throws out error "The 'PySCF' library is required to use 'PySCFDriver'. You can install it with 'pip install 'qiskit-nature[pyscf]''.  See https://pyscf.org/install.html." This problem does not get solved if we just use pip install qiskit-nature[pyscf] or downgrade python to version 3.7. Additionally, pip install pyscf or conda install -c pyscf pyscf does not work for windows 10 OS. Is there any workaround for installing pyscf on windows machine? Otherwise, it means that for using Qiskit Nature in general, we have to stick to Linux or macOS.

**Comment by woodsp-ibm** [comment]
PySCF is not supported on Windows natively, as per your pyscf.org install link, but its is supported on the Windows Subsystem for Linux as that link explains.

Nature allows the use of different classical chemistry library/programs that have different drivers in Nature interfacing with these. See https://qiskit.org/documentation/nature/apidocs/qiskit_nature.drivers.second_quantization.html#drivers for the list and installation information. PyQuante has a pure-Python version that can be used in Windows and is closest in syntax/use to PySCF driver. It is more code used for education etc and while it works its not as capable/powerful as PySCF. You can also use PSI4 on Windows, which is a powerful package for chemistry, though the configuration for this is a little different since PSI4 and the Gaussian (commercial program) drivers are configured using the relevant programs native configuration, which you would need to use. For example for PSI4 here it is being configured in a test https://github.com/Qiskit/qiskit-nature/blob/d6a4db83942cd55c3e23cfbf98497bbc41779594/test/drivers/second_quantization/psi4d/test_driver_psi4.py#L32-L47 though you can use multiline strings too as per here https://github.com/Qiskit/qiskit-nature/blob/d6a4db83942cd55c3e23cfbf98497bbc41779594/test/drivers/second_quantization/psi4d/test_driver_psi4_extra.py#L55-L70

So dependent on your platform there are different drivers you can choose. If you want to stick with PySCF then you need a platform where its supported. But in general no you do not have to stick to Linux or MacOS for Nature as there are multiple drivers supported for each OS.

**Comment by rajarshiche** [comment]
Thanks again @woodsp-ibm. It's very clear and I believe others too can use your comments as resource for qiskit_nature.
