### ISSUE TITLE
Cannot import MatrixOperator

### ISSUE THREAD

**Issue by knc6** [Qiskit/qiskit-metapackage#1413]
Hi,

Thank you for developing the Qiskit package. I have used Qiskit in the [paper](https://iopscience.iop.org/article/10.1088/1361-648X/ac1154/meta) published about a year ago. Also, I have provided a [google colab notebook example](https://colab.research.google.com/github/knc6/jarvis-tools-notebooks/blob/master/jarvis-tools-notebooks/Qiskit_based_electronic_bandstructure_.ipynb) which uses [JARVIS-Tools](https://github.com/usnistgov/jarvis) and [AtomQC](https://github.com/usnistgov/atomqc) packages.

Recently, while re-running the notebook, I found many of the modules have been either moved/renamed or not available. For example I use [`MatrixOperator`](https://github.com/usnistgov/jarvis/blob/217eb3719f9ffce8f2bde9ae73f3961e42660217/jarvis/io/qiskit/inputs.py#L52) from `qiskit.aqua`. 

I tried to search where it could have been moved but I couldn't find any documentation of migrations. This [migration page](https://github.com/Qiskit/qiskit-aqua/blob/main/README.md#migration-guide) seems outdated as well.

Could you please help me find the `MatrixOperator` or its latest updated equivalent? 

Thanks in advance.

**Comment by 1ucian0** [comment]
This issue seems to have cover three things that are related, but maybe helps to answer them independently.
 1. How can I reproduce the result in a paper using a-year-old Qiskit?
 2. Where is `MatrixOperator` that used to be in Aqua?
 3. the migration-guide is outdated.

The first question is probably the one with the most direct answer: You can install the dependencies fixing the versions to the point in which the paper was published. That is means that your first cell should look something like this: `!pip  install "jarvis-tools~=2021.7.5" "qiskit~=0.27"`. This will pin the version to [July 2021](https://pypi.org/project/qiskit/#history) and probably would do the trick if the point is just to reproduce the results you used to have.

For the third part of the issue, do you mind opening a different issue with details on how the migration page needs to be updated?

In the meanwhile, let's jump to the second point, which it seems to be the core of your question. Here, we are going to assume you want to bring your code up to speed with the latest Qiskit, that used to work with Aqua and you want to migrate that. We can keep the topic of this issue on that point. Feel free to open new issues on the others if you would like to follow up that conversation.

---
# Where is `MatrixOperator` now?

https://github.com/usnistgov/jarvis/blob/217eb3719f9ffce8f2bde9ae73f3961e42660217/jarvis/io/qiskit/inputs.py#L52

Your code uses`MatrixOperator` from the module  `aqua.operators` in Aqua. This module used to live [here](https://github.com/Qiskit/qiskit-aqua/blob/main/qiskit/aqua/operators/legacy/matrix_operator.py), in the legacy operator module.

According with the [migration guide](https://github.com/Qiskit/qiskit-aqua#migration-by-packageclass) the module `aqua.operators` was replaced by `qiskit.opflow` in `qiskit-terra`. In your case, you are converting those `MatrixOperator`s into `WeightedPauliOperator`s:

https://github.com/usnistgov/jarvis/blob/217eb3719f9ffce8f2bde9ae73f3961e42660217/jarvis/io/qiskit/inputs.py#L57

so maybe you can use Pauli operators directly. Here is the [documentation about it](https://qiskit.org/documentation/tutorials/operators/01_operator_flow.html#Weighted-sum-of-Pauli-operators).

**Comment by 1ucian0** [comment]
@knc6 if the issue on `MatrixOperator` is solved/explained, can we close it?

**Comment by knc6** [comment]
Yes, I was able solve the issue by pinning the following packages:
```
!pip  install jarvis-tools==2021.7.10 qiskit-terra==0.18.0 qiskit-aer==0.8.2 numpy==1.19.5 matplotlib==3.2.2 requests==2.23.0 scipy==1.4.1 joblib==1.0.1 tqdm==4.41.1 toolz==0.11.1 xmltodict==0.12.0 qiskit-terra==0.18.0 qiskit-aer==0.8.2 qiskit-ibmq-provider==0.15.0 qiskit-ignis==0.6.0 qiskit-aqua==0.9.4
```
