### ISSUE TITLE
Doc building is very slow

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-metapackage#1495]
### What is the expected behavior?

I am trying to build the doc locally and it is taking a really long time ~ 30min. Will need some investigations to find out which part is taking most of the time.

**Comment by jakelishman** [comment]
We know what this is - it's that we have to build the packages and documentation for all of Terra, Aer, IBMQ and run all the tutorials to build the full metapackage's documentation site.

**Comment by jakelishman** [comment]
Since this issue was opened, the build is somewhat faster (about 15 minutes on my machine), which is in the realms of acceptability for now.  It'll get a bit faster still when Terra is responsible for the process, since we'll not need to clone the Terra repo, and faster still when the tutorials are reworked.

I'll close this here, but we'll continue to monitor docs performance when things are moved to Terra.
