### ISSUE TITLE
Divide release note into seperate pages

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-metapackage#1504]
### What should we add?

The [release note page](https://qiskit.org/documentation/release_notes.html) is getting very long. Would it make sense to divide it into separate pages for each release?

**Comment by jakelishman** [comment]
This is to do with the metapackage, because the metapackage is what builds that release notes page.

Separate pages for _every_ release would make it very hard to look through at what's changed in a few old versions, but we could probably stratify it by some other criterion.  The trick is that this is all done very manually by copy-and-paste on releases, and we'd need to set up a bit more structure.  Possibly `0.2x`, `0.3x` and so on could work - for external linking purposes, we'd want to make sure that the release notes for a particular version always have a permanent URL (as best we can).

**Comment by jakelishman** [comment]
This issue is becoming obsolete as the current "release notes" file will become "legacy release notes" on Terra.  We may consider splitting it there, but for now, I'll close this issue as this repository is being sunset.
