### ISSUE TITLE
Aer needs its own documentation page

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#1508]
With the [removal of Aer from the metapackage](https://github.com/Qiskit/qiskit-aer/pull/1526), a documentation page for its own is needed.

Once Aer is removed from the metapackage, the module will be at the same level of other application modules and it will require its own https://qiskit.org/documentation/aer/ in the same way that https://qiskit.org/documentation/nature/ exists, for example.

I suggest creating https://qiskit.org/documentation/aer/ silently with no change in the metapackage documentation first.

**Comment by mtreinish** [comment]
Just for clarification that aer pr does not remove aer from the metapackage. It is creating a new python namespace. The term package there is in the strict python terminology which is confusing for most people: https://docs.python.org/3/glossary.html#term-package

As for the issue this is kinda premature. Aer is still part of the metapackage for now. This issue is also primarily not something we fix in the metapackage repository as publishing self contained docs is done in the aer repository.

**Comment by mtreinish** [comment]
I apologize "premature" probably wasn't the correct way to describe this. Upon reflection renaming the qiskit-aer package from `qiskit.providers.aer` -> `qiskit_aer` is going to have some complications for link preservation. Since when we merge Qiskit/qiskit-aer#1526 the aer docs no longer refer to the old location. We'll probably need to use `sphinx-reredirects` to redirect from the old path to the new one (which likely means indexing everything and redirecting manually, see: https://github.com/Qiskit/retworkx/blob/main/docs/source/conf.py#L125-L128 and https://github.com/Qiskit/retworkx/blob/main/docs/source/sources.txt for what I did in retworkx to go from `retworkx/stubs/*` -> `retworkx/apiref/*`). I think having aer publish a standalone documentation page for it's next release sounds like the best course of action. That's primarily an aer issue, but doing the cleanup for the metapackage side of the docs we can track here.

**Comment by mtreinish** [comment]
I've pushed up https://github.com/Qiskit/qiskit-aer/pull/1589, https://github.com/Qiskit/qiskit/pull/1595, and https://github.com/Qiskit/qiskit/pull/1596 which should address this. Aer will move to a standalone docs build and the main qiskit docs will have redirects from the old aer pages to the new build

**Comment by 1ucian0** [comment]
closed by https://github.com/Qiskit/qiskit-aer/pull/1589
