### ISSUE TITLE
Is there a Chinese documentation here?  

### ISSUE THREAD

**Issue by peng456** [Qiskit/qiskit-metapackage#156]

**Comment by lzdanski** [comment]
Hi! We're working on our new documentation translation strategy right now so that our community members can easily add translated content to the docs. We haven't yet incorporated Chinese documentation yet.

You can track the other work for translations that's ongoing here: https://github.com/Qiskit/qiskit-terra/issues/1677

**Comment by SooluThomas** [comment]
Closing this, because the same is being discussed in issue #610.
