### ISSUE TITLE
"Installation" section of "Getting started" page is empty

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-metapackage#1566]
### Informations

- **Qiskit version**: NA
- **Python version**: NA
- **Operating system**: NA

### What is the current behavior?

[Getting started](https://qiskit.org/documentation/getting_started.html) page has "Installation" section. But, it looks empty.
![image](https://user-images.githubusercontent.com/31178928/178896082-6905981c-9113-4e3b-a24b-df11bfed4f8d.png)

The source rst file contains some texts.
https://github.com/Qiskit/qiskit/blob/master/docs/getting_started.rst#installation

### Steps to reproduce the problem

access: https://qiskit.org/documentation/getting_started.html

### What is the expected behavior?

Show tabs in "Installation" section of https://qiskit.org/documentation/getting_started.html

### Suggested solutions

No idea.

**Comment by HuangJunye** [comment]
Thanks for reporting the bug. I think this is caused by the PR #1558 that migrated `sphinx-panel` to `sphinx-design` extension and forgot to update the directive `tabbed` to the corresponding directive `tab-set` in `sphinx-design`. 

Here is the migration guide: https://sphinx-design.readthedocs.io/en/latest/get_started.html#migrating-from-sphinx-panels

**Comment by t-imamichi** [comment]
I see. I checked the rst files and found that contributing_to_qiskit.rst also contains `tabbed`.
https://github.com/Qiskit/qiskit/blob/master/docs/contributing_to_qiskit.rst#set-up-the-virtual-development-environment
