### ISSUE TITLE
hone getting started

### ISSUE THREAD

**Issue by derivation** [Qiskit/qiskit-metapackage#161]
hone existing getting started with Qiskit material to have it incorporate best practices demonstrated by [Watson Assistant](https://console.bluemix.net/docs/services/assistant/getting-started.html#gettingstarted) and [Google Maps](https://developers.google.com/maps/documentation/javascript/adding-a-google-map).

**Comment by lzdanski** [comment]
Walking through [Getting started with Qiskit](https://learnqiskit.gitbook.io/developers/getting-started-with-qiskit/developing-and-running-quantum-programs), and taking notes on the user experience for this issue. 

**As-is**:
On the general [**Installing Qiskit**](https://qiskit.org/documentation/install.html) page, all installation commands point to `qiskit-aqua`. I would expect to download and install `qiskit` as a new user, installing `qiskit-aqua` seems like I'm not getting the entire package. Maybe a note about what it includes or a description of what you get if you install each of the elements vs `qiskit`?
<img width="704" alt="Screen Shot 2019-04-06 at 8 15 59 AM" src="https://user-images.githubusercontent.com/25642903/55669543-898a2d80-5846-11e9-98da-71fbfe2f5af2.png">

What adds to my confusion is that there's a following link for [**Install Qiskit Terra from Source**](https://qiskit.org/documentation/install/terra.html#install-terra-source). What is the benefit in doing that? Also, this looks like an unindexed topic, it does not appear in the Qiskit docs TOC.

**Suggestions**
- Explain what the differences in installation are, although if it is just a matter of preference, which is the golden path?
- What is the difference between installing elements individually vs Qiskit? Why are our examples sometimes `qiskit-aqua`, `qiskit`, and `qiskit-terra`? 
- **Install Qiskit Terra from Source** is in the qiskit/install directory, which is not included in the TOC. Should we move this file to the qiskit/terra directory and remove the /install directory since there is an `install.rst` topic at the root?

**Comment by lzdanski** [comment]
* Move content from Qiskit Terra from source to Qiskit/terra github repo contributing file
* remove from docs directory

**Comment by lzdanski** [comment]
* How do users verify the installation was successful? What's the equivalent of `qiskit --version`?

* Add line about using python and add `python` to example in [Checking which version is installed](https://qiskit.org/documentation/install.html#install). 
* Add step to end of install procedure for `conda list` to see that the qiskit packages have been installed to [Install Qiskit](https://qiskit.org/documentation/install.html#install)

**Comment by lzdanski** [comment]
https://github.com/Qiskit/qiskit/pull/195

**Comment by derivation** [comment]
@lzdanski in the Install doc, the build Terra from source link points to the Terra contributing file, which then points to a doc page. Could you edit the Terra contributing file to have the install from source instructions directly in the contributing file?
