### ISSUE TITLE
Add a non-Anaconda option for getting started locally

### ISSUE THREAD

**Issue by psschwei** [Qiskit/qiskit-metapackage#1611]
## Does existing documentation need to be updated with new content?

The current ["Getting Started" docs](https://qiskit.org/documentation/getting_started.html#installation) recommends using Anaconda to set up a local environment. However, companies of over 200 people aren't allowed to use the open source (free) version, so it might be good to add another option to support those users (which I imagine would be a non-trivial number of folks). 

This would require an update to `qiskit/docs/getting_started.rst`. 

Perhaps something as simple as using `venv` to create the virtual environment rather than / in addition to `conda`? Could also do something more involved and make the setup not depend on a specific distribution (while still recommending Anaconda).

If this is something of interest, I'm happy to open a PR for it.

**Comment by mtreinish** [comment]
I had been meaning to update that too, I completely forgot about it. Yes, please feel free to push a PR to update the docs there, I've personally never recommended anaconda because of the license terms (and I find it adds too much overhead for how I use things, although I know many people who happily use it). But we should definitely that to say you just need python and maybe some links on how to install it for the supported platforms.

**Comment by psschwei** [comment]
been spoiled by prow :smile:

**Comment by mtreinish** [comment]
Heh, well we do have [qiskit-bot](https://github.com/Qiskit/qiskit-bot) to serve a similar role for some of the automation but it's not as sophisticated as what prow provides for cncf projects. We've mostly concentrated on having it do release automation and notifications to start. But adding assign and other process automation would be an easy and potentially useful addition to it.
