### ISSUE TITLE
Update "About Qiskit" section of the documentation home page

### ISSUE THREAD

**Issue by agebbie** [Qiskit/qiskit-metapackage#1646]
### Feature description

Requesting to update the ["About Qiskit"](https://qiskit.org/documentation/) section of the Documentation homepage to be more inline with the overview features in the ["What is Qiskit" ](https://medium.com/qiskit/what-is-qiskit-your-guide-to-navigating-the-qiskit-cosmos-in-2022-7cc415426f31)blog. 

Link to proposed new language: (TBD)

### Additional context

Would also like to have updated language to add in to this section with links so that we can begin baselining user traffic to the docs.

Will link to the proposed new language in this issue, just need help with implementation!

**Comment by y4izus** [comment]
Since [the text of the Documentation homepage](https://github.com/Qiskit/qiskit/blob/master/docs/index.rst) is on the qiskit repo, I think we should transfer this issue there. @1ucian0 , if you agree, could you transfer the issue, please?

For the language request, I don't fully understand what do you need, sorry @agebbie . Could you create a different issue with your request given more details, please? It's easier for us to have different requests on different issues :) 

Thank you!

**Comment by 1ucian0** [comment]
Closed by https://github.com/Qiskit/qiskit-metapackage/pull/1759
