### ISSUE TITLE
How to upload API key is not shown on Qiskit getting started page

### ISSUE THREAD

**Issue by ajrazander** [Qiskit/qiskit-metapackage#1648]
### Where is the problem?
In the [getting started page]((https://qiskit.org/documentation/getting_started.html).

### What is the problem?
When users go to their account page on https://quantum-computing.ibm.com/account, there is a short description of installing qiskit and accessing real backends next to where users can copy their API key. Step 2 in the short description says, "Follow the instructions to [access the IBM Quantum services from Qiskit](https://qiskit.org/documentation/getting_started.html)." But, the linked website (the qiskit getting started page) does not describe how to save their API key to the IBMQ package.

### What would you expect?
The [getting started page](https://qiskit.org/documentation/getting_started.html) should include the same code as [this page](https://quantum-computing.ibm.com/lab/docs/iql/manage/account/ibmq) to explain how to save a user's API key.

**Comment by jakelishman** [comment]
Since the deprecation of IBMQ Provider, the "Getting Started" guide no longer refers that provider, so the "IBM Quantum Services" link is the correct documentation.  That does (now, at least) include instructions on how to save the token.

I'll close this as completed, but please feel free to re-open if there's more to be said.
