### ISSUE TITLE
Missing default thumbnail for tutorials after nbsphinx 0.9 release

### ISSUE THREAD

**Issue by HuangJunye** [Qiskit/qiskit-metapackage#1707]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

![image](https://user-images.githubusercontent.com/7631333/227500101-cfbacdfa-efba-46e4-8e4d-60c7dfba4eb7.png)

### Steps to reproduce the problem

Go to https://qiskit.org/documentation/tutorials.html

### What is the expected behavior?

The thumbnail default to qiskit logo when it's not set https://qiskit.org/documentation/stable/0.42/tutorials.html

![image](https://user-images.githubusercontent.com/7631333/227500371-47d8b896-25ef-4032-b122-a2968f58aa9a.png)

**Comment by woodsp-ibm** [comment]
See also Qiskit/qiskit_sphinx_theme#221 where I noted this along with the change to the tile sizes/spacing.

**Comment by HuangJunye** [comment]
> See also [Qiskit/qiskit_sphinx_theme#221](https://github.com/Qiskit/qiskit_sphinx_theme/issues/221) where I noted this along with the change to the tile sizes/spacing.

Sorry I missed the issue you filed in the theme repo. Thanks for adding the additional details. I wonder whether we should just pin nbsphinx to <0.9. The 0.9 release doesn't add much new features that we will need.

**Comment by woodsp-ibm** [comment]
We would have to pin in quite a few repos now, I imagine, if that's the choice.

I see here https://github.com/spatialaudio/nbsphinx/releases/tag/0.9.0 it says
> Use the last image in a notebook as the default thumbnail

Another way, given the above, might be to add the sphere image as part of the copyright widget that we add at the end of the notebooks. That widget is in Terra though and since the docs are built/published off stable that seems not so much a short term workaround/fix.

I imagine either would cater to the thumbnail. I did not investigate the style change (size, spacing, colors - is now the standard link colors - purple in this case).

**Comment by woodsp-ibm** [comment]
https://github.com/spatialaudio/nbsphinx/issues/723#issuecomment-1484148667

The nbsphinx issue for default image was commented on - indeed it was changed, but seems there is a way.

**Comment by HuangJunye** [comment]
@Eric-Arellano FYI, this is not a theme issue. The fix should be in the `conf.py` of each sphinx project. So I am going to transfer the issue back to qiskit/qiskit repo

**Comment by woodsp-ibm** [comment]
>  The fix should be in the conf.py of each sphinx project

It seemed we could also drop an .svg image in static, of the right name, which would be picked up on. If that was done I would think the static folder of the deployed docs could be updated on the server so that a fix could be done without republishing, as well of course as adding it to each project. If we kept the former .png file too then things would be more independent of the nbsphinx version.

**Comment by HuangJunye** [comment]
> > The fix should be in the conf.py of each sphinx project
> 
> It seemed we could also drop an .svg image in static, of the right name, which would be picked up on. If that was done I would think the static folder of the deployed docs could be updated on the server so that a fix could be done without republishing, as well of course as adding it to each project. If we kept the former .png file too then things would be more independent of the nbsphinx version.

I don't know how to convert png to svg. I can possibly get an original svg from design team, but I go with the .png file approach because it's faster. You can see here: https://github.com/Qiskit/qiskit/pull/1708. It's a simple fix.

```
nbsphinx_thumbnails = {
    '**': '_static/no_image.png'
}
```
