### ISSUE TITLE
Version list logic in docs doesn't account for patch releases properly

### ISSUE THREAD

**Issue by Eric-Arellano** [Qiskit/qiskit-metapackage#1717]
When the current release is e.g. `0.40.0`, then we don't show `0.40` in the "previous releases" sidebar. That makes sense because the user is already on the current release.

But if the current release is a patch version, like `0.42.1`, then we show `0.42` in the previous releases sidebar. Even though a new patch version should be on the same branch of `stable/0.42` docs.

Probably requires a tweak to `versionutils.py`.

**Comment by jakelishman** [comment]
This is actually caused by the deployment itself - the deployment to `qiskit.org/documentation/` was made on the branch-push event to `master`, which naturally happens _before_ the tag-push event that triggers the push to `qiskit.org/documentation/stable/0.x`.  So the root build occurred before the tag existed, and the version-utils logic was correct in claiming that the new stable version didn't exist yet.

*edit*: as in, the documentation that gets deployed to `/` gets built from a repository state that does not yet have the new tag.  Qiskit/qiskit-terra#10610 changes the logic in the new deployment script so the push to the latest `x.y.0` tag triggers both the `/` and the `/stable/x.y` deployments from the same repo state (and in fact completely equal builds), so the "previous releases" will include `x.y`.
