### ISSUE TITLE
Epic - Move benchmark code out of metapackage

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/qiskit-metapackage#1723]
Following [RFC 0011](https://github.com/Qiskit/RFCs/blob/master/%23%23%23%23-repo-rename.md):

> **benchmarks-out-of-metapackage**: The files in `test/benchmarks` construct <https://qiskit.github.io/qiskit/>. On this, there are the following options:
> 1. Create `qiskit/qiskit-benchmarks` or
> 2. move benchmark code `to Qiskit/qiskit-terra`. It is also possible to continue deploying the results in <https://qiskit.github.io/qiskit/>, in a different github page, or in <https://qiskit.org>.

What are the tasks for doing this?

**Comment by Eric-Arellano** [comment]
I'd bias towards the benchmarks living in Qiskit/qiskit-terra. You get monorepo benefits. Here, in particular:

1. More likely people will pay attention to the benchmarks. Multiple people are using Terra every day, so we will notice e.g. when CI fails
2. We have the option to have benchmarks run against the latest HEAD / PR. Meaning, we can see how a PR impacts performance, which gives us more granularity. (This is an option, not required; we can also choose to only run benchmarks on other events, like Git tags).
3. Less infrastructure, like duplicating Tox files etc.

**Comment by jakelishman** [comment]
I'm not sure I actually see the repo move affecting any of those three points, but I do agree that it makes logical sense for the benchmarks to be in Terra's repo.  An argument against that originally was that the benchmarks were for testing cross-repo performance, so they weren't localised to Terra, but now with the exception of a small dependency on `qiskit-experiments` (iirc, it's just for generating a couple of circuits and isn't involved in the benchmark), it's all Terra.

A benchmark suite run takes ~3 hours; it's not something we can ever run against PRs (so no CI failures from it, etc).  Admittedly that'll fall drastically once we cut the massive waste of time that's the `qiskit.assemble` benchmarks, but even then it'll still be ~45 minutes.  Almost all of the infrastructure is necessarily separate, too; `asv` is configured through its own `asv.conf.json` file, and the machine that actually runs the benchmarks is set up completely separately on the IBM cloud; multi-use public CI VMs aren't suitable for use in benchmarking because we can't control the loading of them.
