### ISSUE TITLE
Failed building wheel for qiskit

### ISSUE THREAD

**Issue by fvarchon** [Qiskit/qiskit-metapackage#197]
### Informations

- **Qiskit version**: 0.8.0
- **Python version**: 3.7.3
- **Operating system**: Windows 10 

### What is the current behavior?
Each time we are doing 'pip install qiskit' in a new python env this message occur after collecting all the packages:
____________________________
Building wheels for collected packages: qiskit, networkx, mpmath, pycparser
  Building wheel for qiskit (setup.py) ... error
  Complete output from command C:\Users\YYYXXX\Anaconda3\envs\terra071\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\YYY~1\\AppData\\Local\\Temp\\pip-install-sk5mb5t0\\qiskit\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\YYY~1\AppData\Local\Temp\pip-wheel-24yyconk --python-tag cp37:
  running bdist_wheel

  ----------------------------------------
  Failed building wheel for qiskit
  Running setup.py clean for qiskit
_____________________________________

At the end **the installation is successful** but the 'Failed building wheel for qiskit' in the middle of the process is always confusing people.
I am not sure it is qiskit related and I think it is not at all a priority but it could be nice to get rid of it at some point in the future.

### Steps to reproduce the problem
In every python env under Windows 10 (problem was also there in windows 7)
pip install qiskit 

### What is the expected behavior?
No 'Failed building wheel for qiskit'

**Comment by yaelbh** [comment]
Happens also on Linux, confused me too (-:

**Comment by mtreinish** [comment]
So that failed to build wheel output is expected it was introduced in #119 (and was the key patch for the 0.7.3 release) as part of a larger workaround. It's safe to ignore and should not be fatal. This is why it successfully installed right after it printed the error. You should be able to actually use qiskit after your first pip command succeeded. 

This has been something that constantly causes confusion for users and I'd like to come up with a way to suppress it. But it's mostly outside our control because failing the wheel build is how we get pip to do what is needed for upgrades from `qiskit<0.7` and pip is what actually outputs that error.

I'm going to close this because it's an expected output (and it also a duplicate of at least one other closed bug on this topic). Feel free to reopen if I'm missing something.

**Comment by fvarchon** [comment]
Sure no problem, thank you for your answer.

**Comment by tigerjack** [comment]
@mtreinish just to let you know that the failure happens also with the latest release on a clean virtual environment. It seems that all the packages were correctly installed by the way.

**Comment by mtreinish** [comment]
> @mtreinish just to let you know that the failure happens also with the latest release on a clean virtual environment. It seems that all the packages were correctly installed by the way.

Yeah, it's still expected and just as before is not fatal. The workaround which causes the failure message hasn't been removed (it probably won't be for the foreseeable future, because we still want to support upgrades from qiskit<0.7.0 to the latest ).

**Comment by gubazoltan** [comment]
Okay so after uninstalling python, qiskit, conda and everything, reinstalling them again for the 5th time.... And this error is not even an error.... okay... got it...

**Comment by lia-approves** [comment]
@mtreinish Would it be reasonable to hard code a different message or omit printing the error message just for that test?  It wouldn't surprise me if someone using qiskit for the first time became discouraged when they saw that qiskit failed to install, even when it succeeded.

**Comment by mtreinish** [comment]
@the-legend-of-lia the problem is that the error messages don't actually get generated by anything qiskit controls. We force the wheel build to fail in order to ensure the upgrade works. But doing that is what causes **pip** to generate and print the error messages. 

I definitely agree it's confusing and discouraging when the error gets printed. That's why for whenever we end up having a 0.11.0 package release we'll probably include: https://github.com/Qiskit/qiskit/pull/304 which removes the workaround and instead documents the manual upgrade steps needed when coming from qiskit < 0.7

**Comment by fyunusa** [comment]
please guys i'm finding it hard to install qiskit  i'm encountering this  (Building wheel for qiskit-terra (setup.py) ... error)

**Comment by fvarchon** [comment]
@umarfarouk98 
At the end, does the installation succeed or not (at this origin it was the case)?

Currently it is difficult to install qiskit with python 3.8.

Could you:
- install Anaconda
- create a python 3.7 environment: conda create --name your_env python=3.7
- conda activate your_env
- pip install qiskit
