### ISSUE TITLE
pip uninstall qiskit only removes terra, not the other components

### ISSUE THREAD

**Issue by robertloredo** [Qiskit/qiskit-metapackage#277]
### Information

- **Qiskit Terra version**: 0.8
- **Python version**: 3.6
- **Operating system**: Mac 10.14.3

### What is the current behavior?

When installing qiskit using pip `pip install qiskit`, it installs various components. 

However, when uninstalling qiskit using pip `pip uninstall qiskit`, it only uninstalls qiskit terra. 

### Steps to reproduce the problem
Uninstall qiskit version 0.8 using `pip uninstall qiskit`

### What is the expected behavior?

Should uninstall all the components which were installed, not just qiskit-terra

### Suggested solutions
Include the uninstall process for qiskit-aer, etc.

**Comment by lerongil** [comment]
I am unable to replicate this. When I `pip uninstall qiskit` I see qiskit 0.10.1 is uninstalled but everything else remains. I do agree that this should uninstall all qiskit components. It is possible that because these are listed in different projects in pypi, we are defaulting to the metapackage. 

@mtreinish should be able to comment on this more.

**Comment by mtreinish** [comment]
Sorry I missed this, yes @lerongil is correct `pip uninstall qiskit` only removes the meta-package, not any of the individual elements, this is because of limitations in pip and it not having a true dependency solver. Each individual element is listed as a requirement of the meta-package so when you run `pip uninstall qiskit` you're saying just uninstall the meta-package. pip is unable to do any more than that like see that the individual elements were only installed as requirements for a now uninstalled package. There are tools out there to try and solve pip's limitations around this such as https://pypi.org/project/pip-autoremove/ though I've never tried any of them (and I only found that one through a  quick search) so I can't recommend them.

Unfortunately, our hands our tied here because of limitations in the python packaging ecosystem. I'm going to close this bug as something we're unable to fix given the limitations of pip. If you think I've missed something please feel free to reopen this and we can continue discussing.

**Comment by richerram** [comment]
Hello, this is a bit old but still happens although I managed to uninstall everything doing `pip uninstall` on every instance of qiskit (terra, aer, aqua etc...) f.ex.
`pip uninstall qiskit-aer`
