### ISSUE TITLE
do we need https://qiskit.org/documentation/advanced_use_of_ibm_q_devices.html

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#290]
my feeling is we dont need. this page. If we do keep it we should make it much simpler it does not need to mimic the notebook

**Comment by lzdanski** [comment]
With updates to the IBMQ provider, I was about to update this topic. I agree that maybe it's redundant since it has so much content that is in the tutorials, but @diego-plan9 made some significant updates to the tutorials which would need to be ported over. 

However, Diego also mentioned that this page is useful as far as giving users a single resource for all things provider related. 

Do we remove the topic (and redirect to tutorial), update the topic with the IBMQ Provider changes from Diego's tutorial, or do we remove/redirect the topic + replace it with a more concise page that does not duplicate the tutorial?

**Comment by nonhermitian** [comment]
This file is more or less one to one with the tutorial and can be dropped.  The added bonus of the tutorial is that it can all be executed to check for bugs.  So the current doc version has bugs (from me), where as the latest tutorial does not.

**Comment by derivation** [comment]
Ok, I'll get rid of this page as follows:

- [x] redirect links to this page to the tutorial
- [x] remove this page from the doc table of contents
- [x] remove the source file for this page
