### ISSUE TITLE
Relax others Qiskit version dependencies

### ISSUE THREAD

**Issue by atilag** [Qiskit/qiskit-metapackage#294]
### What is the expected behavior?
I'm all about depending on specific versions for third-party depedencies, in general it's a good "damage control" strategy, but I'd definitely relax our own Qiskit version depedencies, because we control them and we have better response times in case of an event.
Also, that will give different teams more freedom to patch their components without any further interaction with the rest of the components.
The teams behind the components are the responsible of keeping them in good shape and patch them asap if something is broken.
I'm suggesting to open patch versions like:
```
qiskit-terra >= x.y  
qiskit-aer >= x.y
...
```

**Comment by nonhermitian** [comment]
So I believe @jaygambetta, @mtreinish, myself, and maybe @ajavadia already discussed this issue before we decided to pin the versions.

In essence, the reason behind the separate element repos is to give developers the flexibility to work on their projects without other, disjoint efforts getting in the way.  However we want to offer a coherent software suite.  If we let the versioning be as you propose, then we lose control over what a standard user has installed.  With version pinning we can say that we officially support this combo of packages, rather than we support any combination of various dependencies that satisfy `>=`.  Then when something is wrong, we can use the qiskit version as a guide to what versions of what to look in.    For example, take a look at Matlab (https://www.mathworks.com/help/matlab/ref/ver.html) where you see that their toolboxes (similar to our notion of element here) are tied to the core Matlab release (R2013b in the attached link).

**Comment by jaygambetta** [comment]
yes @atilag I think the overhead of when you update and element increase and releasing an update of the the mega is less then the overhead of debuting the issues people have. You only need to connect your element to the mega not the other elements. 

For this reason I would like to have it strongly correlated.
