### ISSUE TITLE
Need to run the generate_authors script (request from JKU)

### ISSUE THREAD

**Issue by yehuda-naveh** [Qiskit/qiskit-metapackage#326]
Got a request from JKU - they do not appear in the Qiskit AUTHORS file, seems the script has not run since their project was included in Qiskit. Can we run it?

Also, it might be that Robert Wille from JKU, while contributed code, will not be picked up by the script because it was pushed by a single colleague. Can we add him in a way which will not be overridden by the script? (I'm not sure if the script regenerates from scratch each time it runs, or just adds to the existing list)

**Comment by mtreinish** [comment]
Before we can rerun the script and update the authors file we'll need to fix #229 otherwise we'll have to manually curate the list of names again. Once that's fixed it's a simple matter to re-reun the script.

If someone's name isn't on the list and they don't have an entry in git metadata anywhere the script will not put the name in the list. The script and authors file is built using the credited authors from the git log which is the canonical history of contributions. If they're in the git metadata, but credited in another way (not the authors field) then we can add support for that to the script, for example a `Co-Authored-By:` tag (which is already accounted for in the current script) in the commit message. But, from what I can tell Robert Wille is not listed anywhere in the git log for qiskit-jku-provider. In this case where he's clearly listed as an author in the code, but not given credit in any commits, there are 2 ways to move forward, we can either have him push a commit/PR so his name will be picked up by the script. Or we can add his name to the script as a hard coded exception (and clearly document why in a comment) and just remove that in the future if/when he pushes a commit.

**Comment by yehuda-naveh** [comment]
Thanks Matthew, I'll wait for #229 then. 

Yes, I mentioned to Robert the simplest way is to have him push/PR something directly. I'll point him to this issue to decide, either PR something explicitly, or we'll put him as a co-author tag. Hard coding the script is probably not the way to go.

How will we go about on the mailmaps? Someone will do it centrally for all repos? Or one person will do per repo? (If so, I can volunteer for JKU and Ignis), or just all contributors map themselves?

**Comment by mtreinish** [comment]
For the mailmaps someone needs to go and build one for each repo. Feel free to handle to go ahead and push one up for JKU and ignis. If a contributor isn't happy with their name in the authors script they can just edit the mailmap after we create them.

**Comment by yehuda-naveh** [comment]
Done for JKU and Ignis

**Comment by yehuda-naveh** [comment]
Closing this one, #229 covers it

**Comment by mtreinish** [comment]
Just wanted to update here that #401 finally updates the authors script as request. I expect people will want to update mailmaps prior to merging that since there are some raw usernames in there still. But hopefully it will merge soon.
