### ISSUE TITLE
Unexpected Output

### ISSUE THREAD

**Issue by RohitMidha23** [Qiskit/qiskit-metapackage#331]
### Informations

- **Qiskit version**: 0.8.1
- **Python version**: 3.7.3
- **Operating system**: IBM Q Experience

### What is the current behavior?
The current behavior is that `00` and `01` are being generated even though the superposition has been broken and hence `00` and `11` should be generated. 

**Output:** ` {'00': 5071, '01': 4929}`

### Steps to reproduce the problem
```python
backend = Aer.get_backend('qasm_simulator')
c = ClassicalRegister(2)
q = QuantumRegister(2)
circuit = QuantumCircuit(q, c)
circuit.h(q[0])
circuit.measure(q,c)
job = execute(circuit, backend, shots=10000)
job.result().get_counts(circuit)
```
### What is the expected behavior?
Since measurement has been done once superposition has been broken and hence `00` and `11` should be generated as opposed to `00` and `01`. i.e Since measurement has taken place qubit should stay in the same state, which isnt happening here.

**Comment by Matt-Stypulkoski** [comment]
Hi @RohitMidha23, the code you posted would have a measure gate from `q[0] -> c[0]` and `q[1] -> c[1]`. Since your circuit only has an H-Gate on q[0], it is normal for the result to be either `00` or `01`. 

Judging from the question you posted in the Slack, did you mean to have the measurements be written as: `circuit.measure(q[0], c[0])` and `circuit.measure(q[0], c[1])`?

**Comment by Matt-Stypulkoski** [comment]
If you did mean to have the measurements be written out as `circuit.measure(q[0], c[0])` and `circuit.measure(q[0], q[1])`, then I am unable to recreate the issue. When I run your code with these measurements, I get outputs including only `00` or `11`.

**Comment by RohitMidha23** [comment]
Hey @Matt-Stypulkoski yes I understood the mistake. My bad. Closing this issue now
