### ISSUE TITLE
Aqua version issues

### ISSUE THREAD

**Issue by jaygambetta** [Qiskit/qiskit-metapackage#443]
in the https://qiskit.org/documentation/release_notes.html aqua is at version 0.5.3 but according to the qiskit tag in Qiskit-aqua it is at 0.5.5. We should try to keep these in sync. @mtreinish could you look at where the error has occurred.

**Comment by mtreinish** [comment]
Well, I was not aware that there had been any aqua releases since `0.5.3`. According to https://pypi.org/project/qiskit-aqua/#history there was one on July 24th (`0.5.4`) any another on July 26 (`0.5.5`). No one has pushed any updates to the meta-repository corresponding to those releases. The table is actually accurate for what's been included in a meta-package release. When you `pip install qiskit` with the latest meta package version `0.11.1` you'll get aqua 0.5.3 installed.

I'll push up a PR right now to bump things to pull in the latest aqua release.

**Comment by mtreinish** [comment]
Just to follow up here the plan I have moving forward is to use: https://github.com/Qiskit/qiskit-bot on all the repos including aqua. The bot will automatically open a PR here to bump things when a release in an element is pushed.
