### ISSUE TITLE
Move to Read The Docs (RTD) theme

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#467]
We should move to RTD to take advantage of the niceties that others are already using.

https://docs.readthedocs.io/en/stable/index.html

As discussed in #466

**Comment by SooluThomas** [comment]
@nonhermitian I can help you work on this, if you've started. Or else I can give it a try.

**Comment by nonhermitian** [comment]
@SooluThomas said that this is no longer an option due to the requirements of the translations.

**Comment by derivation** [comment]
@SooluThomas, could you write out a few of the reasons here? I think you also mentioned the C/C++ code dependencies of Aer creating a challenge.

**Comment by SooluThomas** [comment]
Yes, we can't adapt RTD due to the following reasons:

- The build for RTD fails due to the C dependencies of Aer. Had discussions with @mtreinish about the same.
- If RTD is used, the current workflow for website deployment including deployment script and translation script will have to be deleted because RTD has a build system of its own and we might have to figure out a way for using CrowdIn for translations.

Steps that we could do next,

- Investigate for a theme or tool, which can build and host multiple versions of our page.

**Comment by nonhermitian** [comment]
There was some confusion here. I just want RTD theme, not the service.
