### ISSUE TITLE
Trouble with visualization

### ISSUE THREAD

**Issue by sunn-e** [Qiskit/qiskit-metapackage#571]
Hi awesome people, this is Sunny, I just came across this and following this(https://www.youtube.com/watch?v=RrUTwq5jKM4) tutorial to get used to the tool. Just for fun. So, I came across a part where I do a hadamard gate operation and draw the circuit usling matplotlib. The video shows a different visual at 4:48 of that video than what I got 
![qiskit](https://user-images.githubusercontent.com/30065288/64937862-8e352200-d879-11e9-8ea5-d320413548e3.png)
 You can notice there is a difference at c0. The classical bits. 
The steps I followed was simple ```circuit.h(qr[0])```
then ```circuit.draw(output='mpl')```
I wonder if those two visuals are same. The tutorial is latest so if there's any changes that happened? 
One more thing, The pinned comment in that video has a typo It is written as 2:10 Build  2 Qbit Register(2)
:

```
qr = QuantumRegistry
```
where as it should be

```
 qr=QuantumRegister(2)
```

**Comment by maddy-tod** [comment]
Hello, glad to see you are enjoying the videos! We have updated it so that the drawings are coloured by default, but the layout of the gates is the same as in the video so they do represent the same circuit. If you draw the circuit with `circuit.draw(output='mpl', style='False')` you should get the black and white drawing as in the video.

**Comment by sunn-e** [comment]
Thanks @maddy-tod , I think you meant ```circuit.draw(output='mpl', style=False)```, It worked for me.
