### ISSUE TITLE
Evaluate tooling and processes for translating Jupyter Notebooks

### ISSUE THREAD

**Issue by lzdanski** [Qiskit/qiskit-metapackage#573]
Identify translation tools to provide multi-language support for tutorials and other materials in Jupyter notebooks.

- Identify tools/toolchain to support multi-language support
    - Investigating markdown (nbtranslate pipeline) and .rst (crowdin pipeline) options

**Comment by mtreinish** [comment]
Not directly related to translations, but a few months ago I did investigate briefly automating the inclusion of the tutorials in the docs: https://github.com/Qiskit/qiskit/pull/42. Doing something like that might enable harvesting the translatable strings from the notebooks for translation. Because the notebooks' rst output will be included at build time so when we run sphinx build with the `gettext` builder they should be included. Although that may not be the direction we want to go on hosting the tutorials so it might not be the best fit.

**Comment by SooluThomas** [comment]
This has been fixed in https://github.com/Qiskit/qiskit/pull/841. Tutorials have been added to the docs. So the .po files for jupyter notebook tutorials are generated correctly and can be translated in crowdin (https://crowdin.com/project/qiskit-docs/settings#files).
