### ISSUE TITLE
https://qiskit.org/documentation/install.html needs a fix!

### ISSUE THREAD

**Issue by a07r** [Qiskit/qiskit-metapackage#660]
I would call it a doc bug 

- https://qiskit.org/documentation/install.html

- Current text is as follows,

We recommend using Python virtual environments to cleanly separate Qiskit from other applications and improve your experience.

The simplest way to use environments is by using the conda command, included with Anaconda. A Conda environment allows you to specify a specific version of Python and set of libraries. Open a terminal window in the directory where you want to work.

Create a minimal environment with only Python installed in it.

conda create -n name_of_my_env python=3
source activate name_of_my_env

- When user abide by the recommendation (above), 
1. Conda would install the latest python version at the time, And Qiskit may or may not be compatible with latest python release. (Current stable version is 3.8 and qiskit isn't compatible yet to python 3.8). Perhaps we can add this piece of information in the html file, notifying the user about the stable python release version. So that new comer's life becomes that much easy!  

2. Documentation doesn't speak about the need to install gcc under new environment that it asks users to create.

- there were few issues created which were closed later, but documentation didn't changed. So someone who goes look up in the closed issue will come to know about the fix. But folks who are just starting up with Qiskit may find it difficult!   

## Does existing documentation need to be updated with new content? -- Yes

- index.html

- If we decide to notify user about the stable python release version then we can simply add a line informing user about it. But this would require repeated updates. (As soon as supported version changes it should be updated for it as well)

- reminding user to install gcc in their new environment should be easy and straight forward approach!

Note: - I want contribute to the community myself, please let me know if I can make these changes myself!

**Comment by derivation** [comment]
@a07r please do give it a shot. We'll review your work. Thank you.

**Comment by a07r** [comment]
@derivation , @lzdanski 

Current status - 

I have opened up a thread in Stack exchange regarding the smartest way possible to make Python version dynamic on documentation -

the same can be accessed at - https://quantumcomputing.stackexchange.com/questions/8720/how-do-i-find-out-which-stable-python-version-qiskit-will-be-compatible-to-at-a

Let me know if you guys have any insights on it, if you guys think it isn't possible at all (and that only with experience one will know which is the stable version) then perhaps I will work towards adding the simple line which reminds user about the need to install GCC on the new anaconda environment.

**Comment by mtreinish** [comment]
I'd argue that the documentation is probably fine, it's just new version updates do not happen in a vacuum and can't happen instantly. Python 3.8 was released less than 1 month ago and the entire python ecosystem is working to both make sure code is updated to work with the new version (because new python versions are never 100% compatible) and push out releases with binary wheels that support the new version (because all packages with compiled extensions need to be rebuilt for new versions). For qiskit this is also true, there are several patches to add python 3.8 support to multiple elements already Qiskit/qiskit-terra#3268 Qiskit/qiskit-aer#428 Qiskit/qiskit-ignis#298 but until this week we weren't even in a place where we could install all of qiskit's upstream dependencies on python 3.8 (and some are still missing, but it's not blocking testing). This is just a temporary blip that is happening right now because of a recent new release of python. It doesn't seem worth the effort to try and restructure things when this will likely all be sorted within the next month and won't be a problem again (well at least for another 12-18 months when python 3.9 is released)

**Comment by a07r** [comment]
I understand/agree, @mtreinish 

I brought it up only to double check if we wanted to address (perhaps mainly because documentation reads 3.5 or later) and from user's (especially someone starting afresh) point of view 3.8 not working can be a bummer and hence brought it up for discussion.

Anyways I guess I will work towards adding the line which let's user know about the need to install GCC under their new conda environment if they choose to create one!

**Comment by a07r** [comment]
@mtreinish @derivation -

There were a few issues reported (see the references above)

 Are we still not doing anything about it?

**Comment by derivation** [comment]
I defer to @mtreinish on this, given his last reply.

**Comment by nonhermitian** [comment]
@a07r, as Matthew mentioned already, packages are working on providing Python 3.8 support.  As such, there as some packages that have yet to provide wheels for Python 3.8, and thus need to be built from source.  This is not something that we need to correct on our part, and is part of the regular Python update cycle.  It just requires time.  Note also that Qiskit is still working on several issues related to Python 3.8, and we are focused on getting that done.

**Comment by a07r** [comment]
@nonhermitian / All,

I understood what @mtreinish said in the first place. 

Currently the documentation reads Python 3.5 or later is stable version to install qiskit, And someone starting afresh would never know Python 3.8 isn't a supported version yet. And just as we've seen issues ( "pip install qiskit failing" ) being reported will keep getting reported. 

I was hoping to get your help in addressing this situation wisely, Cause I simply can't just go and add a line which would let user (new) know that for time being qiskit isn't supported on Python 3.8, for the obvious reason that whenever another new version of python is released we would hit this same bump even then and then someone would have to come back to documentation to update it again. So I wish we could to address this somehow (dynamically) with minimum effort keeping future in mind.   
And hence I seek your help!

**Comment by lzdanski** [comment]
Hi all, this is a tricky docs situation. We don't want to include something that requires constant updates, but we also need to let new users know how to diagnose any installation problems, especially new users, as @a07r has pointed out.

Instead of including specific versions that are causing compatibility issues between Qiskit/Python, this topic really needs to include the process for how to check which version of Python is compatible with Qiskit. 

@mtreinish responded with that info in the [Stack Overflow post](https://quantumcomputing.stackexchange.com/questions/8720/how-do-i-find-out-which-stable-python-version-qiskit-will-be-compatible-to) @a07r created, along with instructions for how to check which specific versions of python are supported by the Qiskit package that is installed by `pip install qiskit`. This was a really useful tip from Matthew that is a good practice for any new user, and it address everyone's concerns.

@derivation and I talked about how we should update this part of the docs. What does everyone think of a change like this?

**Current version:**
Qiskit supports Python 3.5 or later.

**Change to:**

Qiskit supports Python 3.5 or later. However, both Python and Qiskit are evolving ecosystems, and sometimes when new releases occur in one or the other, there can be problems with compatibility.

If you're having trouble installing or using Qiskit after updating Python, check the [Qiskit Package metadata](https://pypi.org/project/qiskit) for **Programming Language** to see which specific versions of Python are supported.
