### ISSUE TITLE
Hadamard Gate not documented: link goes to unrelated page.

### ISSUE THREAD

**Issue by stolk** [Qiskit/qiskit-metapackage#668]
If I go to the GATE documentation here:
https://quantum-computing.ibm.com/support/guides/gate-overview?section=5d00d964853ef8003c6d6820#h-gate

Then there is a link called **"Quantum gates: Hadamard and S"**

Yet, if you click there, you are led to a page about an adder, but NO information whatsoever on Hadamard.

There should be documentation on Hadamard.

**Comment by lzdanski** [comment]
@stolk Thank you for bringing this to our attention! The problem you found isn't really with Qiskit docs, so we're going to make sure this gets to the right group. 

As the fix is being worked on, you can ask questions about the Circuit Composer in the [#ibm-q-experiences channel in the Qiskit Slack](https://join.slack.com/t/qiskit/shared_invite/enQtNjQ5OTc5ODM1ODYyLTc2YWJhOWViZDA2OWI5N2EyMjIxN2YwODM5MWQyN2Q3MjczOGRlMDU4MzMxMWE5MzZjMzEzYzM3MmJiMzU5MzU)
