### ISSUE TITLE
Need listing of which Qiskit versions are currently compatible with IQX API

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-metapackage#757]
### What is the expected behavior?
We need a listing of which Qiskit versions are compatible with the current IQX API.

This was originally in https://github.com/Qiskit/qiskit-terra/issues/1708, but rightfully closed as this is a global Qiskit issue.

This list should be automatically kept up to date.

**Comment by mtreinish** [comment]
I started something along these lines a few months ago here: https://github.com/Qiskit/qiskit-terra/pull/3007

**Comment by mtreinish** [comment]
Oh, sorry I didn't fully read the description before posting the link, just came from the linked issue. They're actually 2 different things one is testing qiskit's api compatibility which is what Qiskit/qiskit-terra#1708 was about and Qiskit/qiskit-terra#3007 was part of addressing by using the iqx tutorials as a test suite. The other being discussed here is about which versions of qiskit are compatible with the IQX REST API. That is actually solely a function of the qiskit-ibmq-provider version because it's the only thing that directly talks to the IQX api. We can add a sphinx function as part of the docs build to determine this but I think it'll just be easier to keep track of when the IQX api introduces a breaking change that requires an ibmq provider update and document that as a line underneath the version table.

**Comment by nonhermitian** [comment]
I agree in the future it will solely be an api issue, but currently that is not the case. Namely because there are things like validation that happen in Terra that can break if a flag changes, but the IQX api still works.

Regardless, we need a way of informing end users exactly what versions are currently working (but perhaps not supported anymore)

**Comment by nonhermitian** [comment]
Closing as stale.
