### ISSUE TITLE
Documentation appears not to link back to source

### ISSUE THREAD

**Issue by Travis-S** [Qiskit/qiskit-metapackage#79]
As far as I can tell, there seems to be no links from the Qiskit documentation back to the source code when looking at the docs for functions (e.g., [`qiskit.circuit.classicalregister`](https://qiskit.org/documentation/autodoc/qiskit.circuit.classicalregister.html)). Having links back to source would be nice for users who need a bit more information.

**Comment by diego-plan9** [comment]
Thanks @Travis-S - will be looked into as part of #80, as we can take the chance to look into the possibility of linking to the repository directly.

**Comment by jaygambetta** [comment]
i think this is what @Travis-S  wants is some way to open the source code. @Travis-S is this correct?

**Comment by Travis-S** [comment]
@jaygambetta Yes. Consider [this documentation for a pyQuil program in Forest](https://pyquil.readthedocs.io/en/stable/apidocs/program.html). If a user wants to read the source code itself, they can click the `source` link (near the declaration of the class) and are taken to [a page where they can read it](https://pyquil.readthedocs.io/en/stable/_modules/pyquil/quil.html#Program).

**Comment by jaygambetta** [comment]
great, i agree. @derivation can you think about the above.

**Comment by derivation** [comment]
I think this would be much appreciated by users. I'll chat with @diego-plan9 and @lzdanski about how to incorporate this practice. Thanks @Travis-S.

**Comment by diego-plan9** [comment]
Thanks for the extended feedback and comments, @Travis-S  - yes, the way we had it setup previously was very similar to the example you mention: we were generating `.html` files for each source file (with syntax highlighting, etc) that were linked from the `autodoc` files (ie. the ones that contain just a description of the functions, arguments, etc). This should be easy to reintroduce (is mostly toggling a flag in the configuration).

What I was trying to suggest was considering, instead of reintroducing those rendered pages as generated .html files, replacing the `source` links with links to the actual files and lines in github. This might provide users with more context about that particular function (and be able to explore github features and the feature history for those inclined to do so), and maybe have the side effect of sparkling contributing or taking a more active role (on the technical side, it also helps a bit with the size of the documentation, as in the terra docs the rendered .html source files were the biggest culprit, but not a strong argument for it).

**Comment by Travis-S** [comment]
@diego-plan9 Absolutely! That would be a great improvement on the original suggestion.

**Comment by diego-plan9** [comment]
I issued #200 for reintroducing the source link using the original approach (ie. include additional rendered .html that contains the source), aiming for the source links being present in the upcoming major release.

For being able to link to github, it would be worth exploring [sphinx.ext.linkcode](http://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html) instead, that offers a `linkcode_resolve()` function that we can tune to return the proper link. The bits that involve more work are being able to deal with multiple versions and repositories, and linking to the specific lines of code (by default, the extension does not provide details about the line numbers) - a source of inspiration can be [the numpy conf.py](https://github.com/numpy/numpy/blob/master/doc/source/conf.py#L303) or similar projects.

**Comment by jaygambetta** [comment]
@Travis-S is this done in the api documentation now.

**Comment by jaygambetta** [comment]
<img width="649" alt="image" src="https://user-images.githubusercontent.com/15731369/63312168-9e83cc80-c2ce-11e9-9258-aea64ffe1d17.png">
