### ISSUE TITLE
Can't install qiskit on Windows with pip version 20.0.1

### ISSUE THREAD

**Issue by vtomole** [Qiskit/qiskit-metapackage#792]
### Informations

- **Qiskit version**: qiskit-0.14.0
- **Python version**: 3.6
- **Operating system**: Windows

### What is the current behavior?
When I upgrade pip to the latest version (20.0.1), I get
```
ERROR: Could not find a version that satisfies the requirement mkl (from cvxopt->qiskit-aqua==0.6.1->qiskit~=0.13.0->-r dev_tools/conf/pip-list-dev-tools.txt (line 18)) (from versions: none)

The command "python -m pip install -r dev_tools/conf/pip-list-dev-tools.txt" failed and exited with 1 during .
```

### Steps to reproduce the problem
`python -m pip install --upgrade pip wheel`
`python -m pip install qiskit`

### What is the expected behavior?
cvxopt should be installed on the system. This is a bug with cvxopt because because `pip install cvxopt` which called `pip install mkl` is what breaks it.

### Suggested solutions
Maybe you could check the pip version that is being used and don't run the install if it's >=20.0.1

**Comment by mtreinish** [comment]
Unfortunately there is nothing we can do about this in the qiskit side. Qiskit code does not get called at any point in that failure. The bug is in pip (this is far from the only issue in pip 20.X.X so far) and probably related to https://github.com/pypa/pip/issues/7626 (I recently had to add a workaround for this issue in qiskit aer's CI too: https://github.com/Qiskit/qiskit-aer/pull/540). I'd recommend you do something similar in your ci setup until pip resolves these issues and pushes out a 20.x.x release that works for everyone.

I'm going to close this issue as there is nothing we can do in qiskit to fix it and it's something pip needs to address. Please feel free to re-open it if I'm missing something or you think there is more to discuss hewe..

**Comment by vtomole** [comment]
Sure. Thanks for that pip issue reference.
