### ISSUE TITLE
Qiskit installation instruction on windows : 

### ISSUE THREAD

**Issue by ibmccmpl** [Qiskit/qiskit-metapackage#801]
# pip install fails - installation instructions for Windows:  
https://qiskit.org/documentation/install.html 
 
Here below the different tests 
 
- **Bare windows qiskit installation** 
   - Get Miniconda Windows installer from https://docs.conda.io/en/latest/miniconda.html 
   - Install Miniconda3 
   - pip install qiskit # installation works perfectly as python package installed is 3.7 (brought by conda)   
 
- **Virtual conda environment qiskit installation**
   - Get Miniconda Windows installer from https://docs.conda.io/en/latest/miniconda.html 
   - conda create -n <qiskit-env> python=3   # T his will install python 3.8.1 in environment
   - pip install qiskit  # fails during Terra and Aer installation, Because pip doesn’t find a package for  python 3.8, it tries to download the source code of Terra and Aer and build it by itself, thus requiring a C++ compiler. This is the misleading error message received: "error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/".   
					   
The misleading error message makes Customers not understanding why a C++ compiler is needed.  And they do not want to install one. If they have VS 2017 installed then the installation fails on cvxopt as a pre-requisite. A 'conda install cvxopt' fixes the problem and running a pip install qiskit again works.  
					   

 - **Using Qiskit on Windows requires VC++ runtime components**
     -  When installing Miniconda3 or Anaconda3, VS 2015 C++ runtime is provided as part of Conda. 
         - Here below the recommendations, aren't they obsolete ?  
            Microsoft Visual C++ Redistributable for Visual Studio 2017
            Microsoft Visual C++ Redistributable for Visual Studio 2015
        - If you install Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.22.27821 or Microsoft Visual C++ 2017 Redistributable (x64) - 14.16.27029 which one will be used ?  the 2015 version from Conda ? one of the version in Windows ?  

- What should the documentation say instead?
Today python 3.8 creates problems when pip install.  The documentation should mention it.  Do we need to install Redistributables if provided in Anaconda3 or Miniconda3.  Unless when installing python only, then windows redistributables need to be recommended  ?

**Comment by nonhermitian** [comment]
This fails due to a downstream dependency, namely cvxopt, that is not Py38 compatible yet. It is also not compatible with our license and has been removed in the master branch.   Qiskit itself was not Py38 compatible itself until just recently. Anytime there is a major Python update packages take time to verify compatibility. Having to change the documentation every time this happens, and then changing it back will just lead to inconsistency as someone must remember to change this and rebuild the docs.

**Comment by patdenim** [comment]
I understand that it is not a solution having constant updates to the documentation.  
Next release of qiskit will support Py38 so this pb will go away. However it would be interresting to let customer know what Python releases are supported by pointing pypi.org for example.  
Also giving simple steps to install qiskit in a bare windows env would help.  Not everyone install in a virtual env.

**Comment by mtreinish** [comment]
So the install documentation already links to the pypi page and says refer to the `Programming Language` section of the package metadata on that page:

https://qiskit.org/documentation/install.html (it's the second sentence)

Do you have a suggested place or alternative wording or formatting for that?

When using a supported version of python `pip install qiskit` should work fine on windows 64 bit (32bit  operating systems aren't supported in general because of aer) because there are precompiled binaries available for everything (except some optional dependencies in aqua). In that situation a venv is not required nor is conda. However, I will say because qiskit still uses namespace packages (at least until #559 is addressed) running in a virtualenv is **strongly** recommended. It gives you and undo button in case the namespace gets out of sync (which happens quite frequently). If your're using a virtualenv you can simply create a new one when that happens, but if the namespace gets broken on system python that's much more difficult to clean up. Also, from personal experience on windows using conda is generally a good idea because it provides precompiled packages for most of the non-python libraries most of the stack requires.

That all being said Qiskit 0.15.0 is out now and includes support for python 3.8 so the underlying problem here has gone away. I'm not going to close this yet though because there might be suggestions on how to improve the documentation more to clear up things here.

**Comment by patdenim** [comment]
honestly i hadn't look at the second sentence :-(
The wording is correct to me. It specifies which specific versions of Python are supported.  Thanks
