### ISSUE TITLE
No matching distribution found for qiskit-chemistry

### ISSUE THREAD

**Issue by beew** [Qiskit/qiskit-metapackage#946]
Hi,

I am trying to reinstall qiskit 0.10.4 for some old codes but I pip install errored out with

```
Could not find a version that satisfies the requirement qiskit-chemistry==0.5.0 (from qiskit==0.10.4) (from versions: none)
ERROR: No matching distribution found for qiskit-chemistry==0.5.0 (from qiskit==0.10.4)
```
OS is Ubuntu 16.04, python-3.7.6. 

But if I just do
```
pip install qiskit
```

Then it installed qiskit 0.14.2 successfully and there is no qiskit-chemistry and 0.14.2 is definitely an old release.

What is going on??

Thanks.

**Comment by t-imamichi** [comment]
Qiskit chemistry was merged into Qiskit Aqua 0.6.
https://github.com/Qiskit/qiskit/blob/master/docs/release_notes.rst#aqua-06-3

**Comment by beew** [comment]
@t-imamichi I found that out after reviewing the release history but it shouldn't be removed retroactively so the old releases are uninstallable.

 Especially since Qiskit keeps changing and it is very challenging to manage codes to make sure that they still run. It is important to make upgrade and downgrade easy if you break  backward compatibility every few releases. e.g tensorflow breaks old compatibility too but it is done in a much more managed  fashion at a much slower pace,  and removing one version to install another is clean and straight forward. But pip uninstall doesn't even remove most pieces in qiskit and one has to hunt down and remove each manually. I think there should a better way to do these things. If you upgrade qiskit and realize that it has some issues you are stuck with a mess.

**Comment by Cryoris** [comment]
You're right, adding more documentation is never a bad idea though this change was mentioned in [the releasenotes](https://qiskit.org/documentation/release_notes.html#notable-changes). I think this can be closed then, right?

**Comment by d4rkc0nd0r** [comment]
It's actually merged to [Qiskit Aqua](https://qiskit.org/aqua/)
For installing Qiskit In Ubuntu, Use  `python -m pip install --user qiskit`
Then in Anaconda, use this `from qiskit import aer` .
Now it works.

**Comment by mtreinish** [comment]
@beew I agree with you it shouldn't have been deleted nor should the source repo have been deleted (it should have been archived and/or moved) it's quite unfortunate that it was, deleting from pypi is almost never the right choice. But, there isn't anything that can be done about it now, once it's deleted from pypi the previously released versions on pypi become locked out and nobody can push new files for the old versions (you can see https://github.com/pypa/packaging-problems/issues/74 for a lengthy discussion about it).

The only remedy I can provide for installing qiskit 0.10.4 manually except for chemistry with `pip install qiskit-terra==0.8.2 qiskit-aer==0.2.1 qiskit-ignis==0.1.1 qiskit-aqua==0.5.1 qiskit-ibmq-provider==0.2.2` (which I just got from https://qiskit.org/documentation/release_notes.html#version-history). The qiskit package is just a metapackage so as long as you're not using qiskit-chemistry everything else should still be installable if you just install the components individually.

But that being said I'm going to close this issue since there isn't anything that can be done. Even if I had a copy of the chemistry tree at time of deletion (which I personally don't someone else might) and could restore a github repo for it, I couldn't upload the old versions to pypi anymore and we'd still be stuck when trying to install `qiskit==0.10.4`. I'm sorry there isn't a better answer here. But please feel free to reopen this if you think I'm overlooking something.

**Comment by beew** [comment]
@SiddTim 

I know but that doesn't allow you to install an earlier version.

**Comment by d4rkc0nd0r** [comment]
@beew 
For earlier version, use  `python -m pip install --user qiskit==0.10.4`

**Comment by beew** [comment]
@SiddTim 

Does not work, this is the whole point of the thread. Please scroll up to read what the issues is. I think only @mtreinish 's way of installing each piece separately works.
