### ISSUE TITLE
API reference of Aqua has gone

### ISSUE THREAD

**Issue by t-imamichi** [Qiskit/qiskit-metapackage#953]
### Informations

- **Qiskit version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

API reference of Aqua is missing in the documentation page.
https://qiskit.org/documentation/apidoc/aqua.html

### What is the expected behavior?

Show it.

**Comment by Cryoris** [comment]
In `qiskit/aqua/docs/apidocs/aqua.rst` we have
```
.. module:: qiskit

=========================
Qiskit Aqua API Reference
=========================

.. toctree::
    :maxdepth: 2

    qiskit_aqua
    qiskit_chemistry
    qiskit_finance
    qiskit_ml
    qiskit_optimization
```
I might be wrong, but shouldn't this list the directories without the leading `qiskit_`? Comparing to `terra.rst` or `ignis.rst` they show only the directory names.

On the other hand, the Aqua apidocs haven't been touched since 2 months and before it worked, so it might be a build issue. @woodsp-ibm might know more about this.

Note that just the landing page seems to be missing, other pages still exist: https://qiskit.org/documentation/apidoc/qiskit.aqua.operators.html.

**Comment by mtreinish** [comment]
This will be fixed by #951 in the short term. Only paths that result in ignis tomography being imported are missing because of a bug in the recent ignis release causing an error on import

**Comment by Cryoris** [comment]
Nice, do you know when the docs will be re-built, or does this happen automatically?

**Comment by mtreinish** [comment]
It happens automatically, you can track the job here: https://github.com/Qiskit/qiskit/actions/runs/143434185

**Comment by mtreinish** [comment]
#951 has merged and the docs upload job has finished and corrected the issue. I'm going to close this now, feel free to reopen it if I'm missing something.

**Comment by t-imamichi** [comment]
Thanks!
